uglySite/urls.py
from . import views
from django.urls import path



urlpatterns = [
    path('', views.landing, name="landing"),
    path('category/<str:categoryName>/', views.category, name="category"),
    path('product<int:identifier>/', views.product, name="product"),
    path('search/<str:text>/', views.search, name="search"),
    path('checkout/', views.checkout, name="checkout"),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe-webhook'),
    path('succeed/', views.succeed, name="succeed"),
    path('error/', views.error, name="error"),
    path('loading/', views.loading, name="loading"),
    path('policy/', views.policy, name="policy"),
    path('extended-policy/', views.extendedPolicy, name="extendedPolicy"),
    path('shipping/', views.shipping, name="shipping"),
    path('hechopor/', views.madeby, name="madeby"),
    path('loadCustom/<str:ID>/', views.loadCustom, name="loadCustom"),
    #path('madeby/', vies.madeBy, name="madeBy")
]

uglysocks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uglySite.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uglySite/models.py
from django.db import models
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_delete


@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.FileField):
            instance_file_field = getattr(instance,field.name)
            delete_file_if_unused(sender,instance,field,instance_file_field)
            
def delete_file_if_unused(model,instance,field,instance_file_field):
    dynamic_field = {}
    dynamic_field[field.name] = instance_file_field.name
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)

# Create your models here.
class Product (models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField('Precio', max_digits=10, decimal_places=2)
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    mainImage = models.ImageField(upload_to="uploads", null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    categories = models.JSONField(null=True, blank=True)
    reviews = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    custom = models.BooleanField(default=False, null=True, blank=True)
    backImage = models.ImageField(upload_to="uploads", null=True, blank=True)

    def __str__(self):
        return self.name

class ProductImage (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="uploads")

    def __str__(self):
        return self.product.name

class Order (models.Model):

    STATUS_OPTIONS = [
        ('RM', 'Remove'),
        ('PN', 'Pendiente'),
        ('EP', 'En proceso'),
        ('EN', 'Enviada'),
        ('RE', 'Recibida')
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    received = models.DateTimeField(null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=2, choices=STATUS_OPTIONS, default='RM')
    products = models.JSONField(null=True, blank=True)
    #{  
    #   "name": ...,
    #    "email": ...
    #}

    def __str__(self):
        return str(self.id)

class Address(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField('Nombre(s)', max_length=100, null=True, blank=True)
    lastname = models.CharField('Apellidos', max_length=100, null=True, blank=True)
    country = models.CharField('País', max_length=150, null=True, blank=True)
    street = models.CharField('Calle y número (ext)', max_length=150, null=True, blank=True)
    innerNum = models.IntegerField("Número interior", null=True, blank=True)
    city = models.CharField('Ciudad', max_length=150, null=True, blank=True)
    region = models.CharField('Región/Provincia', max_length=150, null=True, blank=True)
    postalCode = models.IntegerField('Código Postal', null=True, blank=True)
    email = models.EmailField('Correo electrónico', max_length=254, null=True, blank=True)
    phone = models.CharField('Teléfono', max_length=150, null=True, blank=True)
    shipping = models.BooleanField(default=True)

    def __str__(self):
        return self.street

class Review (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    reviewer = models.CharField("Nombre *", max_length=100)
    review = models.TextField("Reseña *")
    email = models.EmailField("E-mail *")
    published = models.BooleanField(default=False)
    rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.reviewer

class StripeReceipt (models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    receipt = models.JSONField()

    def __str__(self):
        return str(self.id)

class CustomImage(models.Model):

    STATUS_OPTIONS = [
        ('RM', 'Remove'),
        ('PN', 'Pendiente'),
        ('EP', 'En proceso'),
        ('EN', 'Enviada'),
        ('RE', 'Recibida')
    ]

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    front = models.ImageField("Frente", upload_to="uploads/custom/", null=True, blank=True)
    back = models.ImageField("Atrás", upload_to="uploads/custom/", null=True, blank=True)
    status = models.CharField(max_length=2, choices=STATUS_OPTIONS, default='RM')

    def __str__(self):
        return str(self.uuid)

uglySite/views.py
from django import forms
from django.shortcuts import render, redirect
from .forms import SearchForm, ReviewForm, CheckoutForm, CheckoutForm1, CartForm, CustomImagesForm, CustomImagesURLForm
from .models import Product, ProductImage, Review, Order, Address, StripeReceipt, CustomImage
import stripe
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.conf import settings
import uuid
from uglysocks import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from email.mime.image import MIMEImage
from django.contrib.staticfiles import finders
import re
from io import BytesIO
from django.core.files import File
import base64
from PIL import Image

stripe.api_key = "sk_test_0q9BNL8DVS1X1xS1u46YyA1M00RmBsmehw"

# Create your views here.


#Easter egg

def loadCustom(request, ID):
    try:
        image = CustomImage.objects.get(uuid=uuid.UUID(ID))
        return HttpResponse(image.front.url,content_type="application/str")
    except:
        return HttpResponse("",content_type="application/str")




def landing(request):

    
    
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            text1 = form.cleaned_data["text"]
            return redirect('/search/' + text1.lower())


    context = {
        "form": SearchForm(),
    }
    return render(request, 'landing.html', context)


def category(request, categoryName):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            text1 = form.cleaned_data["text"]
            return redirect('/search/' + text1.lower())

    
    productList = Product.objects.filter(categories__categories__contains=categoryName)
    listLength = productList.count()

    context = {
        "form": SearchForm(),
        "productList": productList,
        "searchName": categoryName,
        "listLength": listLength,
        "notFound": "Ups! Parece que no hay ninguna categoría llamada ("+categoryName+")",

    }
    return render(request, 'search.html', context)

def make_image(image, name, size=(1000,4500)):
    im = Image.open(BytesIO(image))
    im.resize(size, Image.ANTIALIAS)
    thumb_io = BytesIO()
    im.save(thumb_io, "PNG", quality=100)
    thumbnail = File(thumb_io, name=name)
    return thumbnail

def product(request, identifier):

    product = Product.objects.get(pk=identifier)
    categoryName = product.categories["categories"][0]
    gallery = ProductImage.objects.filter(product=product)
    relProd = Product.objects.filter(categories__categories__contains=categoryName).exclude(pk=product.id)[:4]
    reviews = Review.objects.filter(product=product).filter(published=True)
    images=""


 
    try:
        objCheck = CustomImage.objects.get(uuid=settings.IMG_UUID)
        if objCheck != None:
            settings.IMG_UUID = uuid.uuid4()
    except: 
        print("No obj found!")
        print("UUID: ", settings.IMG_UUID)

    imguuid = settings.IMG_UUID

    ratSum = 0.0
    for r in reviews:
        ratSum+=float(r.rating)

    numOfReviews=reviews.count()
    product.reviews=numOfReviews
    if numOfReviews > 0:
        product.rating=ratSum/numOfReviews
    else:
        product.rating=0.0
    product.save()

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            text1 = form.cleaned_data["text"]
            return redirect('/search/' + text1.lower())

        form2 = ReviewForm(request.POST)
        if form2.is_valid():
            review = Review(
                product=product,
                reviewer=request.POST.__getitem__("reviewer"),
                review=request.POST.__getitem__("review"),
                email=request.POST.__getitem__("email"),
                rating=abs(float(request.POST.__getitem__("rating")))
            )
            review.save()
            
            return redirect("product", identifier=identifier)
        


        form4 = CustomImagesForm(request.POST)
        if form4.is_valid():

            #try:
                if "uuid" in request.POST:
                    if str(imguuid) == request.POST.__getitem__("uuid"):
                        if "fronturl" in request.POST and "backurl" in request.POST:
                            if request.POST.__getitem__("fronturl")!="" and request.POST.__getitem__("backurl")!="":
                                frontstr = re.search(r'base64,(.*)', request.POST.__getitem__("fronturl")).group(1)
                                backstr = re.search(r'base64,(.*)', request.POST.__getitem__("backurl")).group(1)
                                img = CustomImage(
                                    uuid=imguuid,
                                    front=make_image(base64.b64decode(frontstr), str(imguuid)+".png", size=(1000,4500)),
                                    back=make_image(base64.b64decode(backstr), str(imguuid)+".png", size=(1000,4500)),
                                )
                                img.save()
                                settings.IMG_UUID = uuid.uuid4()
                                return HttpResponse(
                                    json.dumps({"uuid": str(img.uuid), "newuuid":   str(settings.IMG_UUID), "fronturl": str(img.front.url), "success": "True",}),
                                    content_type="application/json"
                                )
                            elif request.POST.__getitem__("fronturl")!="":
                                frontstr = re.search(r'base64,(.*)', request.POST.__getitem__("fronturl")).group(1)
                                img = CustomImage(
                                    uuid=imguuid,
                                    front=make_image(base64.b64decode(frontstr), str(imguuid)+".png", size=(1000,4500)),
                                )
                                img.save()
                                settings.IMG_UUID = uuid.uuid4()
                                return HttpResponse(
                                    json.dumps({"uuid": str(img.uuid), "newuuid":   str(settings.IMG_UUID), "fronturl": str(img.front.url), "success": "True",}),
                                    content_type="application/json"
                                )
                            elif request.POST.__getitem__("backurl")!="":
                                backstr = re.search(r'base64,(.*)', request.POST.__getitem__("backurl")).group(1)
                                img = CustomImage(
                                    uuid=imguuid,
                                    back=make_image(base64.b64decode(backstr), str(imguuid)+".png", size=(1000,4500)),
                                )
                                img.save()
                                settings.IMG_UUID = uuid.uuid4()
                                return HttpResponse(
                                    json.dumps({"uuid": str(img.uuid), "newuuid":   str(settings.IMG_UUID), "fronturl": str(img.front.url), "success": "True",}),
                                    content_type="application/json"
                                )

                        elif "fronturl" not in request.POST and "backurl" in request.POST:
                            if request.POST.__getitem__("backurl")!="":
                                backstr = re.search(r'base64,(.*)', request.POST.__getitem__("backurl")).group(1)
                                img = CustomImage(
                                    uuid=imguuid,
                                    back=make_image(base64.b64decode(backstr), str(imguuid)+".png", size=(1000,4500)),
                                )
                                img.save()
                                settings.IMG_UUID = uuid.uuid4()
                                return HttpResponse(
                                    json.dumps({"uuid": str(img.uuid), "newuuid":   str(settings.IMG_UUID), "fronturl": str(img.front.url), "success": "True",}),
                                    content_type="application/json"
                                )
                                
                        elif "fronturl" in request.POST and "backurl" not in request.POST:
                            
                            if request.POST.__getitem__("fronturl")!="":
                                frontstr = re.search(r'base64,(.*)', request.POST.__getitem__("fronturl")).group(1)
                                img = CustomImage(
                                    uuid=imguuid,
                                    front=make_image(base64.b64decode(frontstr), str(imguuid)+".png", size=(1000,4500)),
                                )
                                img.save()
                                settings.IMG_UUID = uuid.uuid4()
                                return HttpResponse(
                                    json.dumps({"uuid": str(img.uuid), "newuuid":   str(settings.IMG_UUID), "fronturl": str(img.front.url), "success": "True",}),
                                    content_type="application/json"
                                )                 
                    else:
                        print("MMM That's not the uuid")
                        return redirect("/error/", errorMsg="Algo salió mal.")
            #except:
                #return redirect("/error/", "Algo salió mal.")

    
    context = {
        "form": SearchForm(),
        "product": product,
        "gallery": gallery,
        "reviewForm": ReviewForm(),
        "numOfRev": numOfReviews,
        "reviews": reviews,
        "relProd": relProd,
        "customProduct": product.custom,
        "cartForm": CartForm(),
        "customImages": images,
        "CustomImagesURLForm": CustomImagesURLForm(),
        "imagesForm": CustomImagesForm(),
        "uuid": imguuid,
    }

uglySite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    {% block head %}
    <head>
        <title>Ugly Socks</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
        {% block extra_css %}
        {% endblock extra_css %}
    </head>
    {% endblock head %}

    {% block body %}
    <body>

        <div class="page-container" id="page-container">
            {% block toolbar %}
            <div class="menu">
                <div class="toolbar">
                    <span class="helper"></span>
                    <img id="logo" src="{% static 'images/white_logo-100x100.png' %}">

                    <div class="actions">
                        <div class="verticalSeparator"></div>

                        <form class="searchBox" method="POST">
                            {% csrf_token %}
                            {{form}}

                            <button type="submit">
                                <img src="{% static 'images/lupa.svg' %}">
                            </button>
                        </form>

                        <div id="cartIcon" class="cart">
                            <span class="helper"></span>
                            <img  src="{% static 'images/carro.svg' %}">
                            <div id="miniCartTotal"></div>
                        </div>

                        <div id="miniCartFilter" display="none"></div>

                        <div id="miniCart" style="display: block;">
                            <div class="miniCartContent">
                                <div class="miniTop">
                                    <img id="miniCloser" src="{% static 'images/close.svg' %}">
                                    <div class="miniTitle">Carrito: </div>
                                </div>
                                
                                <div class="miniList">
                                    <ul id="miniUl">
                                    </ul>
                                </div>

                                <div class="miniFooter">
                                    <div id="miniTotal"></div>
                                    <div id="toCheckout">Proceder al pago.</div>
                                </div>
                            </div>
                        </div>

                        <span class="helper"></span>
                    </div>
                </div>


                
            </div>

            <div class="toolbarSpacer"></div>
            {% endblock toolbar %}

            {% block content %}
            {% endblock content %}

            {% block footer %}
            <div class="footer" id="real-footer">
                <span class="helper"></span>
                <div class="row">
                    <ul>
                        <li>Si tienes alguna duda, escríbenos a <a href="mailto:contacto@ibarraransoftware.com">contacto@ibarraransoftware.com</a></li>
                        <li><a href="{% url 'shipping' %}">Acerca de los envíos.</a></li>
                        <li><a href="{% url 'policy' %}">Política de privacidad.</a></li>
                        <li><a href="{% url 'madeby' %}">Hecho por...</a></li>
                    <ul>
                </div>
            </div>
            <div class="fake-footer" id="fake-footer"></div>
            {% endblock footer %}
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"></script>
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <script type="text/javascript">
            document.getElementById("logo").onclick = function(){
                window.location = "{% url 'landing' %}";
            };
        </script>

        {% block extra_js %}
        {% endblock extra_js %}

    </body>
    {% endblock body %}
</html>

uglySite/templates/loading.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Ugly Socks</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/loading.css' %}">
    </head>

    <body>
        <div class="container"><div class="loader"></div></div>
    </body>
</html>

uglySite/templates/madeby.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div style="text-align: center;">
    <img style="max-width: 70vw; max-height: 70vh; margin: 5% auto;" src="{% static 'images/madeby.png' %}">
</div>
{% endblock content %}

uglySite/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
{% endblock extra_css %}

{% block content %}
<div class="product">
    <div class="PI">
        <ul>
            <li class="image-selected" id="li0" onClick="makeMain(this, 0)"><span class="helper"></span><img class="secondary" id="img0" src="{{product.mainImage.url}}"></li>

            {% if product.custom %}
            <li class="" id="li1" onClick="makeMain(this, 1)"><span class="helper"></span><img class="secondary" id="img1" src="{{product.backImage.url}}"></li>
            {% else %}

                {% for image in gallery %}
                <li id="li{{forloop.counter}}" onClick="makeMain(this, {{forloop.counter}})"><span class="helper"></span><img class="secondary" id="img{{forloop.counter}}" src="{{image.image.url}}"></li>
                {% endfor %}

            {% endif %}

        </ul>
        <div class="main">
            <span class="helper"></span>
            <img id="main-image" src="{{product.mainImage.url}}">
        </div>

        <div id="zoom-indicator" style="display:none;"></div>
        <div id="zoom-area" style="background-image: url('{{ product.mainImage.url }}');background-color: #000; display: none;"></div>
    </div>
    <div class="PT">
        <ul class="stars">    
            {% if product.rating > 0.00 %}
                {% if product.rating > 1.00 %}
                    {% if product.rating > 2.00 %}
                        {% if product.rating > 3.00 %}
                            {% if product.rating > 4.00 %}
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            {% else %}
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                            <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                            {% endif %}
                        {% else %}
                        <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                        <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                        <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                        <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                        <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                        {% endif %}
                    {% else %}
                    <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                    <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                    <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                    <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                    <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                    {% endif %}
                {% else %}
                <li><img class="gold" src="{% static 'images/emptyStar.png' %}"></li>
                <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                <li><img class="gray" src="{% static 'images/emptyStar.png' %}"></li>
                {% endif %}                    
                <div class="numOfRev">({{numOfRev}})</div>
            {% endif %}
        </ul>
        <div class="name">{{product.name}}</div>
        <div class="PR">${{product.price}}</div>
        <div class="colorPicker"><span>Click para seleccionar el color del producto:</span><input type="color" id="COLPICK" value="#000000"></div>


        
            {% if customProduct %}
            <div>
                <form id="imagesForm" method="POST">
                {% csrf_token %}
                    <div class="imageUploader">
                        <div class="title">Imágenes en calcetín:</div>
                        <div class="order">- De preferencia, súbelas con fondo transparente y una medida de 1000 x 4500 px.</div>
                        <div class="tip">Tip: Edita tus diseños en canva antes de subirlos.</div>
                        <div class="myR">
                            <span class="helper"></span>
                            <table class="files">
                                {{imagesForm.as_table}}
                            </table>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
        


        <div class="cart">
            <span class="helper"></span>
            <div class="quantity">
                <span class="helper"></span>
                <img id="qLess" src="{% static 'images/less.svg' %}">
                {{cartForm}}
                <img id="qMore" src="{% static 'images/more.svg' %}">
            </div>
            <button type="submit" id="addtocart">
                <span class="helper"></span>
                <div>Añadir al carrito</div>
                <img src="{% static 'images/carro.svg' %}">
            </button>
        </div>

        
        <div class="extra">
            <div class="selector">
                <div id="description" style="font-weight:bold;">Descripción: </div>
                <div id="reviews">Valoración y reseñas:</div>
            </div>

            <div class="D" id="D">
                {{product.description}}
                <img src="{% static 'images/pagos.png' %}">
            </div>
            <div class="V" id="V" style="display:none;">

                
                <div class="rateProd">
                    {% if product.rating > 0 %}
                    
                    <div class="noRev">Deja una reseña. <span class="eighty">Tu correo no será visible.</span></div>
                    {% else %}
                    <div class="noRev">Aún no hay reseñas. Sé el primero en dejar una! <span class="eighty">Tu correo no será visible.</span></div>
                    {% endif %}
                    <form class="revForm" method="POST">
                        {% csrf_token %}
                        <div class="setStars">
                            <span>Valoración *:</span>
                            <img id="setStar1" class="gray" src="{% static 'images/emptyStar.png' %}">
                            <img id="setStar2" class="gray" src="{% static 'images/emptyStar.png' %}">
                            <img id="setStar3" class="gray" src="{% static 'images/emptyStar.png' %}">
                            <img id="setStar4" class="gray" src="{% static 'images/emptyStar.png' %}">
                            <img id="setStar5" class="gray" src="{% static 'images/emptyStar.png' %}">
                        </div>
                        
                        <table class="formTable">{{reviewForm.as_table}}</table>
                        <input type="number" name="rating" step="0.1" id="id_rating" style="display:none;">
                        <button type="submit">Submit</button>
                    </form>
                </div>

                {% if numOfRev > 0 %}
                <div class="reviews">
                    {% for rev in reviews %}
                        <div class="review">
                            
                            <div>
                                <span class="reviewer">{{rev.reviewer}}</span>
                                <div class="starss">
                                    <img class="gold" src="{% static 'images/emptyStar.png' %}"> 
                                    <span class="helper"> </span>
                                    <div class="rating">{{rev.rating}}</div>
                                </div>
                            </div>

                            <div class="rev">{{rev.review}}</div>
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if not product.custom %}
<div class="relProd">
    <hr>
    <div class="relText">Productos relacionados: </div>
    <div class="grid">
        {% for prod in relProd %}
        <div class="product" id="product{{prod.id}}">
            <a href="/product{{prod.id}}"><img src="{{prod.mainImage.url}}"></a>
            <div class="PT2">
                <div class="name">{{prod.name}}</div>
                <div class="price">${{prod.price}}</div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}


<canvas id="ghost" width="1000" height="1000" style="display: none;"></canvas>
<canvas id="ghost-front" width="1000" height="4500" style="display: none;"></canvas>
<canvas id="ghost-back" width="1000" height="4500" style="display: none;"></canvas>
<img id="ghost-img-front" style="display: none;">
<img id="ghost-img-back" style="display: none;">
<img id="ghost-img" style="display: none;">
<img id="ghost-img1" style="display: none;">

{% endblock content %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/jquery-form/form@4.3.0/dist/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
<script type="text/javascript">
    var prodNum = "{{product.id}}";
    var prodName = "{{product.name}}";
    var prodPrice = "{{product.price}}";
    var page_url = "{{ request.path }}";
    var customProd = "{{product.custom}}";
    {% if product.custom %}
    var uuid = "{{uuid}}";
    var new_uuid = "{{uuid}}";
    {% endif %}
</script>
<script type="text/javascript" src="{% static 'js/product.js' %}"></script>

{% endblock extra_js %}